---
title: "ANES media bias"
author: "Tyler Garner"
date: "2022-12-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libs-and-data}
library(tidyverse)

anes <- read_csv("data/raw/anes_timeseries_2020_csv_20220210.csv",
                 show_col_types = FALSE)
```

```{r}
dim(anes)
head(anes)
```

Select columns to use for K-NN imputing

```{r}
anes2 <- anes %>%
  select(V201001:V201658p) # pre-election survey vars
         # V202001:V202645n, # post-election survey vars
         # V203400:V203416) # interviewer description vars

# Remove vars with zero variance
non_zero_vars <- sapply(anes2, function(x) length(unique(x))) %>%
  as.data.frame() %>%
  filter(. > 1) %>%
  rownames()

anes2 <- anes2 %>%
  select(all_of(non_zero_vars))

# In media vars convert -9 (Refused) and -5 (Interview breakoff (sufficient partial IW)) to NA
anes2 <- anes2 %>%
  mutate(across(V201629a:V201636k, ~ ifelse(. < -1, NA, .)))

# sum(apply(anes2, 1, function(x) all(!is.na(x))))
```


```{r}
# Use KNN imputation to fill in missing values
library(caret)
library(doParallel)

n_cores <- parallel::detectCores()
cl <- makeForkCluster(n_cores)
registerDoParallel(cl)

anes9 <- anes2 %>%
  select(V201629a:V201636k)

set.seed(4960)
preProcValues <- preProcess(anes9,
                            "bagImpute",
                            k = 20,
                            knnSummary = median,
                            verbose = TRUE)

# preProcValues$data gets set as a tibble and the predict function does not like it, so force it to
# a data frame then make predictions
# preProcValues$data <- data.frame(preProcValues$data)

impute_anes_info <- predict(preProcValues,
                            anes9,
                            verbose = TRUE)
                            # na.action = na.pass)

stopCluster(cl)

# # Select the vars of interest (media vars)
# anes3 <- impute_anes_info %>%
#   select(V201629a:V201629e, # media types
#          V201630a:V201630s, # political shows 1
#          V201631a:V201631s, # political shows 2
#          V201633a:V201633r, # radio programs
#          V201634a:V201634s, # websites
#          V201635a:V201635k, # newspapers
#          V201636a:V201636k) # online newspapers

# Check that there are no NA values
sum(is.na(impute_anes_info))

saveRDS(impute_anes_info, 'data/interim/imputed-media-vars.RDS')
```

Select the columns of interest

```{r}
# Bind the weights, party affiliation, and empathy var columns
anes3 <- anes %>%
  select(V200010a:V200010d, # weights
         V201018, # party affiliation
         V202451:V202456) %>% # empathy questions
  bind_cols(impute_anes_info)

hist(anes3$V201634s)
```

```{r}
adfontes <- read_csv('data/raw/adfontes.csv') %>%
  mutate(Media = factor(Media))
```

```{r}
adfontes %>%
  group_by(Media) %>%
  summarize(mean_rel = mean(Reliability, na.rm = TRUE),
            mean_bias = mean(Bias, na.rm = TRUE))
```

```{r}
hist(adfontes$Bias, breaks = 10)
hist(adfontes$Reliability, breaks = 10)

plot(adfontes$Bias,
     adfontes$Reliability)
```


```{r}
# Keep only the media vars that have Reliability and Bias scores
media_codes <- adfontes %>%
  drop_na() %>%
  pull(Code)
  
anes4 <- anes3 %>%
  select(all_of(media_codes))

# Convert all -1 to 0
anes4 <- anes4 %>%
  mutate(across(everything(), ~ replace(., . == -1, 0)))

anes4_bias <- anes4 * adfontes$Bias[match(names(anes4), adfontes$Code)][col(anes4)]
anes4_rel <- anes4 * adfontes$Reliability[match(names(anes4), adfontes$Code)][col(anes4)]

anes4$Total_Bias <- rowSums(anes4_bias)
anes4$Total_Rel <- rowSums(anes4_rel)

# Get the average Bias and Reliability based on the media consumed for each respondant
# This will create NaN values for respondents with all 0 values
anes4$Avg_Bias <- anes4$Total_Bias / rowSums(anes4_bias != 0)
anes4$Avg_Rel <- anes4$Total_Rel / rowSums(anes4_rel != 0)

# Replace NaN values with 0
anes4 <- anes4 %>%
  mutate(across(c(Avg_Bias, Avg_Rel), ~ replace(., is.nan(.), 0)))

hist(anes4$Avg_Bias)
hist(anes4$Avg_Rel)
```

```{r}
# Bind the weights, party affiliation, and empathy var columns
anes_bias_rel <- anes %>%
  select(V200010a, # pre-election data weights
         V201018, # party affiliation
         V202451:V202456) %>% # empathy questions
  bind_cols(anes4)
```

```{r}
empathy1 <- anes_bias_rel %>%
  select(!V202452:V202456) %>%
  filter(V202451 > 0)

empathy1_lm <- lm(V202451 ~ Avg_Rel * Avg_Bias,
                  data = empathy1,
                  weights = V200010a)
summary(empathy1_lm)

ggplot(empathy1,
       aes(y = factor(V202451),
           x = Avg_Bias * (1 / (Avg_Rel + 0.001)))) +
  geom_boxplot() +
  scale_x_reverse()
```

