---
title: "Imputation with MICE"
author: "Tyler Garner"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load in the data set and remove all of the variables with zero variance (have only a single value).  Also drop all response variables.

```{r load-libs-and-data, warning = FALSE}
library(mice)
library(tidyverse)

anes <- read_csv("data/raw/anes_timeseries_2020_csv_20220210.csv",
                 show_col_types = FALSE)

# Keep only pre- and post-election vars
anes <- anes %>%
  select(!c(V200001:V200016d, V203000:V203527))

# Remove response vars
anes <- anes %>%
  select(!c(V202541a:V202547, V201114:V201123, V202451:V202456, V201626:V201627, V201639:V201640))

# Remove vars with 0 variance
n_unique <- apply(anes, 2, function(x) length(unique(x)))

cols_to_keep <- names(n_unique)[n_unique > 1]

anes <- anes %>%
  select(all_of(cols_to_keep))
```

```{r}
# Get the names of all media vars of interest
anes_media_vars <- anes %>%
  select(V201630a:V201630r, # TV programs 1
         V201631a:V201631r, # TV programs 2
         V201633a:V201633r, # Radio programs
         V201634a:V201634c,V201634e:V201634f, V201634h,
         V201634j:V201634q, # Websites not included in 'online newspapers'
         V201636a:V201636d) %>% # Online newspapers
  colnames()

# In media vars convert -9 (Refused), -5 (Interview breakoff (sufficient partial IW)), and
# -1 (inapplicable) to NA
anes_to_impute <- anes %>%
  mutate(across(all_of(colnames(anes_media)),
                ~ ifelse(. < 0, NA, .)))
```

```{r}
anes_imputed <- quickpred(anes_to_impute,
                          mincor = 0.5,
                          method = 'spearman')
```




